# Tensor

#### From python list to pytorch tensor

In [3]:
a = [1.0, 2.0, 4.0]
a[2], a[1], a[0] # to access the elements

(4.0, 2.0, 1.0)

#### Constructing our first tensors
Let’s construct our first PyTorch tensor and see what it looks like. It won’t be a particularly  meaningful tensor for now, just three ones in a column:

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

#### The essence of tensors

In [5]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Here, we pass a list of lists to the constructor. We can ask the tensor about its shape:

In [10]:
points.shape

torch.Size([3, 2])

This informs us about the size of the tensor along each dimension. We could also use
zeros or ones to initialize the tensor, providing the size as a tuple:

In [11]:
points1 = torch.zeros(3, 4)
points1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Now we can access an individual element in the tensor using two indices:

In [12]:
points = torch.tensor([[4.0, 3.0],[9.0, 5.0],[1.0, 7.0]])
points

tensor([[4., 3.],
        [9., 5.],
        [1., 7.]])

In [15]:
points[0, 1], points[2, 0], points[2, 1]

(tensor(3.), tensor(1.), tensor(7.))

In [17]:
points[2]

tensor([1., 7.])

### Indexing tensors
What if we need to obtain a tensor containing all points but the first? That’s easy using
range indexing notation, which also applies to standard Python lists. Here’s a
reminder:

In [18]:
some_list = list(range(10))

In [19]:
some_list[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
some_list[:8]

[0, 1, 2, 3, 4, 5, 6, 7]

In [21]:
some_list[4:]

[4, 5, 6, 7, 8, 9]

In [23]:
some_list[-1]

9

In [24]:
some_list[:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
some_list[1:6:2]

[1, 3, 5]

In [26]:
points[1:]

tensor([[9., 5.],
        [1., 7.]])

In [27]:
points[1:, :]

tensor([[9., 5.],
        [1., 7.]])

In [35]:
points[1:, 0]

tensor([9., 1.])

### Named tensors

In [40]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])
print('img_t shape is: ', img_t.shape)
batch_t = torch.randn(2, 3, 5, 5) # shape(batch, channels, rows, columns)
print('batch_t shape is: ', batch_t.shape)

img_t shape is:  torch.Size([3, 5, 5])
batch_t shape is:  torch.Size([2, 3, 5, 5])


So sometimes the RGB channels are in dimension 0, and sometimes they are in dimension 1. But we can generalize by counting from the end: they are always in dimension –3, the third from the end. The lazy, unweighted mean can thus be written as follows:

In [37]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[-0.9475, -0.2048,  0.5480, -1.0728,  0.5295],
        [-0.2186, -0.8791, -0.2718, -0.0185,  0.8655],
        [-0.2684, -0.2551, -0.0142, -0.3518, -0.2456],
        [-0.5062, -0.8001,  0.4826, -0.3146,  0.1570],
        [ 0.4514, -0.0372,  0.2800,  0.0095, -0.4125]])

In [38]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive.

tensor([[[-0.2658, -0.8273,  0.5968,  0.5962, -0.5514],
         [ 1.0178,  0.2745, -0.6927,  0.0365, -0.1473],
         [ 0.2558,  0.0508,  0.2296,  0.8286, -0.0568],
         [-0.7043, -0.4299, -0.7622, -0.4874, -0.3776],
         [-0.5070, -0.1756,  0.8048, -0.0311,  0.0963]],

        [[ 0.5076, -0.4662, -0.1701,  0.5970,  0.5589],
         [-0.1031,  0.2303,  0.6683, -0.1983,  0.8043],
         [ 1.0771,  0.3059, -0.0527, -1.0095,  0.2989],
         [ 0.1800,  0.2465, -0.2021,  0.1847,  0.5674],
         [-0.8276, -0.6394, -0.0555, -0.3065, -0.0972]]])

In [39]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [58]:
print('weights are: ', weights)
u_wei = weights.unsqueeze(-1)
print(u_wei)

weights are:  tensor([0.2126, 0.7152, 0.0722])
tensor([[0.2126],
        [0.7152],
        [0.0722]])


In [43]:
# unsqueezed weights are
unsqueezed_weights = u_wei.unsqueeze_(-1)
print('now the weights is:', unsqueezed_weights)

now the weights is: tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])


In [66]:
x = torch.zeros(2, 1, 2, 1, 2, 1, 3, 1, 4, 1, 8)
print('x size: ',x.size())
y = torch.squeeze(x, 5).squeeze_(-2)
print('y size; ', y.size())
z = torch.unsqueeze(x, 5).unsqueeze_(-1)
print('z size; ', z.size())

x size:  torch.Size([2, 1, 2, 1, 2, 1, 3, 1, 4, 1, 8])
y size;  torch.Size([2, 1, 2, 1, 2, 3, 1, 4, 8])
z size;  torch.Size([2, 1, 2, 1, 2, 1, 1, 3, 1, 4, 1, 8, 1])


In [71]:
unsqueezed_wieghts = weights.unsqueeze(-1).unsqueeze_(-1)
print(f'unsqueeze weights are : {unsqueezed_weights.size()}')
img_weights = img_t * unsqueezed_weights
print(f'img weights are : {img_weights.size()}')
batch_weights = (batch_t * unsqueezed_weights)
print(f'batch weights are: {batch_weights}')
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

unsqueeze weights are : torch.Size([3, 1, 1])
img weights are : torch.Size([3, 5, 5])
batch weights are: tensor([[[[ 1.3410e-01,  4.1412e-02,  1.8624e-01, -2.4739e-01, -8.3834e-03],
          [ 2.6002e-02,  1.1006e-01,  2.6604e-02, -1.5176e-01,  1.1341e-01],
          [ 5.2646e-03,  8.3194e-02,  9.1663e-03,  5.2155e-02,  3.9999e-01],
          [ 5.5885e-02,  2.0322e-01,  7.0203e-02, -4.6984e-02, -4.1005e-01],
          [ 1.7054e-01,  4.9045e-02, -2.9808e-01,  1.9825e-01, -1.2489e-01]],

         [[-5.7764e-01, -2.0459e-02,  3.5363e-01,  3.3748e-01, -7.9933e-01],
          [-6.3657e-01, -4.4475e-01, -5.1425e-01, -4.5333e-01,  6.2717e-01],
          [ 4.2966e-01, -2.0583e-01, -2.9130e-01,  1.0615e+00,  3.8507e-01],
          [ 6.8312e-01, -3.7356e-01, -7.5505e-01,  9.8167e-01, -8.2856e-02],
          [-6.8794e-01, -2.6783e-02, -1.7324e+00,  1.4238e+00, -2.1522e+00]],

         [[-4.5049e-02,  8.4379e-02, -5.1102e-02,  3.1131e-02, -1.1852e-02],
          [ 1.9891e-01, -3.9633e-02, -9.7409

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [72]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [73]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/tmp/ipykernel_34946/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484772832/work/c10/core/TensorImpl.h:1408.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [74]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


The method align_as returns a tensor with missing 
dimensions added and existing ones permuted to the right order:

In [77]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

Functions accepting dimension arguments, like sum , also take named dimensions:

In [80]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

### Tensor element types