# Tensor

#### From python list to pytorch tensor

In [3]:
a = [1.0, 2.0, 4.0]
a[2], a[1], a[0] # to access the elements

(4.0, 2.0, 1.0)

#### Constructing our first tensors
Let’s construct our first PyTorch tensor and see what it looks like. It won’t be a particularly  meaningful tensor for now, just three ones in a column:

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

#### The essence of tensors

In [5]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Here, we pass a list of lists to the constructor. We can ask the tensor about its shape:

In [10]:
points.shape

torch.Size([3, 2])

This informs us about the size of the tensor along each dimension. We could also use
zeros or ones to initialize the tensor, providing the size as a tuple:

In [11]:
points1 = torch.zeros(3, 4)
points1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Now we can access an individual element in the tensor using two indices:

In [12]:
points = torch.tensor([[4.0, 3.0],[9.0, 5.0],[1.0, 7.0]])
points

tensor([[4., 3.],
        [9., 5.],
        [1., 7.]])

In [15]:
points[0, 1], points[2, 0], points[2, 1]

(tensor(3.), tensor(1.), tensor(7.))

In [17]:
points[2]

tensor([1., 7.])

### Indexing tensors
What if we need to obtain a tensor containing all points but the first? That’s easy using
range indexing notation, which also applies to standard Python lists. Here’s a
reminder:

In [18]:
some_list = list(range(10))

In [19]:
some_list[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
some_list[:8]

[0, 1, 2, 3, 4, 5, 6, 7]

In [21]:
some_list[4:]

[4, 5, 6, 7, 8, 9]

In [23]:
some_list[-1]

9

In [24]:
some_list[:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
some_list[1:6:2]

[1, 3, 5]

In [26]:
points[1:]

tensor([[9., 5.],
        [1., 7.]])

In [27]:
points[1:, :]

tensor([[9., 5.],
        [1., 7.]])

In [35]:
points[1:, 0]

tensor([9., 1.])

### Named tensors

In [1]:
import torch
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])
print('img_t shape is: ', img_t.shape)
batch_t = torch.randn(2, 3, 5, 5) # shape(batch, channels, rows, columns)
print('batch_t shape is: ', batch_t.shape)

img_t shape is:  torch.Size([3, 5, 5])
batch_t shape is:  torch.Size([2, 3, 5, 5])


So sometimes the RGB channels are in dimension 0, and sometimes they are in dimension 1. But we can generalize by counting from the end: they are always in dimension –3, the third from the end. The lazy, unweighted mean can thus be written as follows:

In [2]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[-0.3551, -0.1090,  0.9420,  0.0174, -0.6883],
        [-0.5484, -0.8165,  0.6246,  0.1676,  0.4834],
        [-0.4048,  0.4419,  0.1145,  0.4918,  0.2158],
        [ 1.3552,  0.1854,  0.3461, -0.8790,  0.1873],
        [ 1.2316,  0.1752,  0.2710, -0.1936,  0.1626]])

In [3]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive

tensor([[[ 0.4027,  0.7604, -0.0985, -0.2641,  0.0270],
         [-0.1788,  0.2909,  0.2093,  0.3123, -1.7091],
         [ 0.8682,  0.0338, -1.1168, -0.6875,  0.1586],
         [-0.8242, -0.4347,  0.7018,  0.7854, -0.4348],
         [-0.4783,  0.1403, -0.6714, -0.5326, -0.1283]],

        [[ 0.5973, -0.5245,  0.0135, -0.8498, -1.2132],
         [ 0.2407, -0.1070, -0.2181, -0.4211,  0.4640],
         [ 0.2991, -0.4971, -1.2940, -0.4065, -0.9677],
         [-0.1969,  0.4618,  0.5780, -0.1594, -0.3836],
         [ 0.2466,  0.0106, -0.3765, -0.3065,  0.4799]]])

In [4]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
print('weights are: ', weights)
u_wei = weights.unsqueeze(-1)
print(u_wei)

weights are:  tensor([0.2126, 0.7152, 0.0722])
tensor([[0.2126],
        [0.7152],
        [0.0722]])


In [8]:
# unsqueezed weights are
unsqueezed_weights = u_wei.unsqueeze_(-1)
print('now the weights is:', unsqueezed_weights)

now the weights is: tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])


In [6]:
x = torch.zeros(2, 1, 2, 1, 2, 1, 3, 1, 4, 1, 8)
print('x size: ',x.size())
y = torch.squeeze(x, 5).squeeze_(-2)
print('y size; ', y.size())
z = torch.unsqueeze(x, 5).unsqueeze_(-1)
print('z size; ', z.size())

x size:  torch.Size([2, 1, 2, 1, 2, 1, 3, 1, 4, 1, 8])
y size;  torch.Size([2, 1, 2, 1, 2, 3, 1, 4, 8])
z size;  torch.Size([2, 1, 2, 1, 2, 1, 1, 3, 1, 4, 1, 8, 1])


In [9]:
unsqueezed_wieghts = weights.unsqueeze(-1).unsqueeze_(-1)
print(f'unsqueeze weights are : {unsqueezed_weights.size()}')
img_weights = img_t * unsqueezed_weights
print(f'img weights are : {img_weights.size()}')
batch_weights = (batch_t * unsqueezed_weights)
print(f'batch weights are: {batch_weights}')
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

unsqueeze weights are : torch.Size([3, 1, 1])
img weights are : torch.Size([3, 5, 5])
batch weights are: tensor([[[[-5.7215e-02,  1.5508e-01, -2.9824e-01,  1.3168e-01,  2.3311e-01],
          [ 8.4736e-03, -1.3555e-01, -1.2420e-01, -1.5637e-01, -2.2515e-01],
          [-4.0311e-03, -2.9236e-01, -7.8649e-02,  1.0788e-02,  1.3535e-01],
          [-2.8815e-01, -1.6792e-02,  4.6567e-02,  3.3994e-01, -2.0604e-01],
          [-1.0433e-01,  6.4154e-02,  9.5768e-02, -1.6151e-01, -1.2768e-01]],

         [[ 2.1108e-02,  1.9739e-01, -1.8772e-02, -7.6927e-01, -4.6154e-02],
          [ 9.4499e-01,  4.5625e-01,  7.9695e-01,  1.2977e+00, -7.2436e-01],
          [ 9.6404e-01,  6.8166e-01, -1.4187e+00, -7.8108e-01,  3.9437e-01],
          [-7.3646e-01, -2.4148e-01,  5.6921e-01,  8.8831e-01, -5.6055e-01],
          [-2.4972e-01,  2.1033e-01, -2.8539e-01,  3.7206e-01, -1.2981e-01]],

         [[ 1.0452e-01,  9.2103e-02,  8.1833e-02, -2.4266e-02, -6.8656e-02],
          [-1.3700e-01,  6.2993e-02,  7.0672

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [10]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [11]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/tmp/ipykernel_5567/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484772832/work/c10/core/TensorImpl.h:1408.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [12]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


The method align_as returns a tensor with missing 
dimensions added and existing ones permuted to the right order:

In [13]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

Functions accepting dimension arguments, like sum , also take named dimensions:

In [14]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

If we try to combine dimensions with different names, we get an error:

In [15]:
gray_named = (img_named[..., :3]* weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [16]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

### Tensor element types

#### specifying the numeric type with dtype
Here’s a list of the possible values for the ```dtype``` argument:
- ```torch.float32``` or ```torch.float```: 32-bit floating-points
- ```torch.float64``` or ```torch.doule```: 64-bit, double-precision floating-points
- ```torch.float16``` or ```torch.half```: 16-bit, half precision floating-point
- ```torch.int8```: signed 8-bit integers
- ```torch.uint8```: unsigned 8-bit integers
- ```torch.int16``` or ```torch.short```: signed 16-bit integers
- ```torch.int32``` or ```torch.int```: signed 32-bit integers
- ```torch.int64``` or ```torch.long```: signed 64-bit integers
- ```torch.bool```: Boolean

However the some basic element of the operation that help:
- Tensor can be used ias indexes in other tensors. In this case, Pytorch expects indexing tensor to gave a 64-bit integer data type. Creating a tensor with integers as arguments, such as using ```torch.tensor([2,2])```, will create a 64-bit integer tensor by default.
- But we'll speand most of our time dealing with ```float32``` and ```int64```. 
- Predicates on tensors, such as ```points > 1.0```, produce bool tensors indicating wheather each individual elements satisfies the condition.

#### Managing a tensor’s dtype attribute
- To allocate a tensor of the right numeric type, we can specifi=y the proper ```dtype``` as an argument to the constructor. For example

In [18]:
double_points = torch.ones(10, 2, dtype = torch.double)
short_points = torch.tensor([[1, 2],[3, 4]], dtype= torch.short)

We can find out about the ```dtype``` for a tensor by accessing the corresponding attribute:

In [19]:
short_points.dtype

torch.int16

We can also cast the output of a tensor creation function to the right type using the
corresponding casting method, such as

In [20]:
double_point = torch.zeros(10, 2).double()
short_point = torch.ones(10, 2).short()

We can make it more convenient to method:

In [ ]:
double_pin = torch.zeros(10, 2).to(torch.double)
short_pin = torch.ones(10, 2).to(dtype=torch.short)

When mixing input types in operations, the inputs are converted to the larger type
automatically. Thus, if we want 32-bit computation, we need to make sure all our
inputs are (at most) 32-bit:

In [22]:
points_64 = torch.rand(5, dtype = torch.double)
points_shorts = points_64.to(torch.short)
points_64 * points_shorts # works from pytorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

### The tensor API

the vast majority of operations on and between tensors are available in the
```torch``` module and can also be called as methods of a tensor object. For instance, the
```transpose``` function we encountered earlier can be used from the ```torch``` module

In [23]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

or as a method of the a tensor:

In [26]:
b = torch.ones(3, 2)
b_t = b.transpose(0, 1)

b.shape, b_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [1]:
import torch

In [2]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [3]:
points_storage = points.storage()
points_storage[2]

5.0

In [4]:
points.storage()[2]

5.0

For instance, the ```zero_``` method zeros out all the elements of the input.
Any method without the trailing underscore leaves the source tensor unchanged and
instead returns a new tensor:

In [5]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Tensor metadata: Size, offset, and stride

#### Views of another tensor’s storage

In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [8]:
second_point.size()

torch.Size([2])

In [9]:
second_point.shape

torch.Size([2])

In [10]:
points.stride()

(2, 1)

### Moving tensors to the GPU
n addition to ```dtype``` , a PyTorch ```Tensor``` also has the notion of ```device``` , which is whereon the computer the tensor data is placed. Here is how we can create a tensor on the GPU by specifying the corresponding argument to the constructor:

In [1]:
import torch
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [4]:
points_gpu = points.to(device='cuda:0')

In [5]:
points_gpu = 2*points.to(device='cuda')

In [6]:
points2 = 2*points

If we add a constant tot he result

In [7]:
points_gpu = points_gpu + 4

In order to move the tensor back to
the CPU, we need to provide a ```cpu``` argument to the ```to``` method, such as

In [8]:
points_cpu = points_gpu.to(device='cpu')

We can also use the shorthand methods cpu and cuda instead of the to method to
achieve the same goal:
```python3
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()
```

In [9]:
torch.version.cuda

'11.7'

### NumPy interoperability
To get a NumPy array out of our ```points``` tensor, we just call

In [10]:
points = torch.ones(5, 5)
points_np = points.numpy() # convert tensor to numpy
points_np

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

Conversely, we can obtain a PyTorch tensor from a NumPy array this way:

In [12]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Here’s how we can save our ```points``` tensor to an ourpoints.t file:

In [13]:
torch.save(points, '/home/mahfuz/Desktop/dlpyt/p1ch3/outpoints.t')

In [16]:
# alternative way
with open('/home/mahfuz/Desktop/dlpyt/p1ch3/outpoint1.t', 'wb') as f:
    torch.save(points, f)

Loading our points back is similarly o one-liner

In [18]:
points = torch.load('/home/mahfuz/Desktop/dlpyt/p1ch3/outpoints.t')

# alternative way
with open('/home/mahfuz/Desktop/dlpyt/p1ch3/outpoint1.t', 'rb') as f:
    point1 = torch.load(f)

#### erializing to HDF5 with h5py
We can install h5py using

In [ ]:
!